### PR TITLE
Changes in Function calls and Copyright year

### PR DESCRIPTION
**Pull request by jobinsjohn**
The function calls have been updated to Swift 2.2 and the Copyright year has been updated.

### CODE REVIEW

**Comment by MosheBerman** [comment]
Hey, it's beneficial to have the earliest possible copyright date, so I'm not going to merge this. The Swift 2.2 update is useful, so if you isolate it, I'll give it a look.

**Comment by ArtSabintsev** [comment]
@MosheBerman This guys is doing the same thing on some of my repos as well. he also attempted to change attribution to his name in the PR.

**Comment by MosheBerman** [comment]
@ArtSabintsev Ouch - got a link?

**Comment by ArtSabintsev** [comment]
Here you go: https://github.com/ArtSabintsev/MaterialSwitch/pull/2/files

Some old repo I built once as an example of something.

**Comment by MosheBerman** [comment]
Ah, eep!

**Pull request closed without merging**
